---
kind: pipeline
type: docker
name: un-nom

steps:
  - name: preact-app
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} app
      - cd app
      - npm install
  - notify:
      image: plugins/slack
      secrets: [ slack_webhooks ]
      channel: drone-cli
      username: Gopher
      template: >
        {{#success build.status}}
        {{/success}}
