---
kind: pipeline
type: docker
name: un-nom

steps:
  - name: preact-app
    image: lowess/preact-cli
    commands:
      - export BASE_URL=${DRONE_REPO_OWNER}.github.io/preact-cli
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} app
      - cd app
      - npm install
      - npm run build
      - npm run build:preview
  - name: publish
    image: plugins/gh-pages
    settings:
      username: Hatsumi-FR
      password:
        from_secret: PW_GH
      pages_directory: app/dist
  - name: notify
    image: plugins/slack
    settings:
      channel: drone-ci
      webhook:
        from_secret : SLACK_WEBHOOKS
      username: Gopher
      template: >
        {{#success build.status}}
        Go > JS
        {{/success}}
        by {{build.author}}
