---
kind: pipeline
type: docker
name: un-nom

steps:
  - name: preact-app
    image: lowess/preact-cli
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} app
      - cd app
      - npm install
  - name: notify
    image: plugins/slack
    channel: drone-ci
    settings:
      webhook:
        from_secret : SLACK_WEBHOOKS
      username: Gopher
      template: >
        {{#success build.status}}
        Go > JS
        {{/success}}
